### ISSUE TITLE
MMI_splitter_3D_FDFD issue

### ISSUE THREAD

**Issue by YUJING-HE** [anstmichaels/emopt#24]
I have encountered a problem when running ~/emopt-master/examples/MMI_splitter_3D/mmi_1x2_splitter_3D_fdfd.py

[INFO] Building system matrices...
Traceback (most recent call last):
  File "mmi_1x2_splitter_3D_fdfd.py", line 203, in <module>
    sim.build()
  File "~/emopt-master//emopt/fdfd.py", line 2772, in build
    self.buildA(l)
  File "~/emopt-master//emopt/fdfd.py", line 2482, in buildA
    A[i, jEx] = 1j*eps.get_value(xh+0.5*divl,yh,zh-0.5*divl) # todo: partial grid steps
  File "PETSc/Mat.pyx", line 276, in petsc4py.PETSc.Mat.__setitem__
  File "PETSc/petscmat.pxi", line 1072, in petsc4py.PETSc.mat_setitem
  File "PETSc/petscmat.pxi", line 825, in petsc4py.PETSc.matsetvalues
  File "PETSc/arraynpy.pxi", line 140, in petsc4py.PETSc.iarray_s
  File "PETSc/arraynpy.pxi", line 121, in petsc4py.PETSc.iarray
TypeError: Cannot cast array data from dtype('complex128') to dtype('float64') according to the rule 'safe'

It seems that the data types of Maxwell operator and its elements are not consistent.

**Comment by YUJING-HE** [comment]
I have already solve the problem by reconfiguring the installation of PETSc
PETSc configure option : --with-scalar-type=complex
